sudo: required
language: csharp
mono: none
dotnet: 2.1

branches:
  except:
    # this is required to avoid building tags.
    - /^v?\d+\.\d+\.\d+(\w*\W*)*$/
script:
  # NOTES: both packages (the library and the global tool) are strongly version coupled (don't want to create a new repo for such tiny code :)
  # the library (so you can import an use it on cf4dotnet projects)
  - sed -i -e "s/000/${TRAVIS_BUILD_NUMBER^^}/g" $TRAVIS_BUILD_DIR/src/library/Cloudformation4dotNET.Library.csproj
  - dotnet pack $TRAVIS_BUILD_DIR/src/library -c release -o $TRAVIS_BUILD_DIR/artifacts/library
  # the cf4dotnet global tool 
  - sed -i -e "s/000/${TRAVIS_BUILD_NUMBER^^}/g" $TRAVIS_BUILD_DIR/src/tool/Cloudformation4dotNET.csproj  
  - dotnet build $TRAVIS_BUILD_DIR/src/tool -c release -o $TRAVIS_BUILD_DIR/artifacts/tool
deploy:
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push $TRAVIS_BUILD_DIR/artifacts/tool/NachoColl.Cloudformation4dotNET.*.nupkg --api-key $NUGET_APIKEY --source https://www.nuget.org && dotnet nuget push $TRAVIS_BUILD_DIR/artifacts/library/NachoColl.Cloudformation4dotNET.Library.*.nupkg --api-key $NUGET_APIKEY --source https://www.nuget.org
    on: master 
