sudo: required
language: csharp
mono: none
dotnet: 2.1

branches:
  except:
    # this is required to avoid building tags.
    - /^v?\d+\.\d+\.\d+(\w*\W*)*$/
    # dev brach should not be published.
    - dev
script:
  - echo $TRAVIS_BUILD_DIR
  - dotnet build -c release "$TRAVIS_BUILD_DIR\src\" -o $TRAVIS_BUILD_DIR\build
deploy:
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push $TRAVIS_BUILD_DIR\NachoColl.AWSCloudformationGenerator4dotNET.*.nupkg $NUGET_APIKEY --source https://www.nuget.org 
    on: master 
